library(stringr)
library(ggplot2)
theme_set(theme_classic())
library(dplyr)
library(tidyr)
library(tibble)
library(readr)
library(maps)
library(glue)
library(cowplot)
library(phyloseq)
library(forcats)
library(vegan)
library(patchwork)
library(seriation)
library(purrr)
library(shiny)
library(microViz)
library(UpSetR)
library(indicspecies)
library(ggrepel)
library(paletteer)
library(viridis)
library(ggtext)
library(tibbletime)
library(lubridate)

#DESeq2
library("DESeq2")
library("pheatmap")
library("RColorBrewer")
library("apeglm")
library("DEGreport")

set.seed(1)

#Colours for cycle
colours_cycle <- readxl::read_excel(here("init_files", "colours_cycle.xlsx"))
colours_cycle <- structure(colours_cycle$colour,.Names=colours_cycle$cycle)

# Colours for sample type
sample_colour <- c("#7EC3E5", "#0F6B99", "#333333",  "#00F100", "#996035")
sample_list <- c("water_CTD", "water_pump", "trap_fix", "trap_live", "core")
sample_palette <- structure(sample_colour,.Names=sample_list)
