---
title: "ancom test"
format: html
---

```{r echo=TRUE, message=FALSE, warning=FALSE}
# # Install from Bioconductor
# if (!requireNamespace("BiocManager", quietly = TRUE))
#     install.packages("BiocManager")
# 
# BiocManager::install("ALDEx2")

# Load package
library(ALDEx2)

library(here)

source(here("init_files", "init.R")) #for libraries
# source(here("init_files", "init_markdown.R")) #for markdown libraries
source(here("init_files", "define_functions.R")) #functions to 1.transform to dataframe, 2.normalise and 3.create treemaps

set.seed(1)
library(purrr)
# library(EnhancedVolcano)

# Subdivision palette
divisionPalette <- readxl::read_excel("init_files/division_palette.xlsx")
divisionPalette <- structure(divisionPalette$colour,.Names=divisionPalette$subdivision) 
```

# ALDEx2 from phyloseq function
```{r}
phyloseq_run_aldex <- function(ps) {
  counts <- as(otu_table(ps), "matrix")
  
  # Ensure taxa are rows
  if (!taxa_are_rows(ps)) {
    counts <- t(counts)
  }
  
  meta <- sample_data(ps)
  conds <- as.character(meta$sample_depth)
  print(conds)
  
  x <- aldex.clr(counts, conds, mc.samples=128, verbose=F, gamma=0.20)
  x.tt <- aldex.ttest(x, hist.plot=F, paired.test=FALSE, verbose=FALSE)
  x.effect <- aldex.effect(x, CI=T, verbose=F, include.sample.summary=F, paired.test=FALSE)
  
  x.all <- data.frame(x.tt,x.effect) %>%
    rownames_to_column(var = "ASV")
  
  taxa <- as.data.frame(tax_table(ps))
  
  x.taxa <- full_join(x.all, taxa)
  
  return(x.taxa)
}
```

# load data
```{r}
source(here("init_files", "read_data_v3.R")) #load phyloseq and modify variables
ps_all
source(here("init_files", "filt_samples.R")) #filter out replicates, blanks etc. 
ps
```



# subset phyloseq
```{r}
deseq.subset <- ps %>%
  # combine depth 1+2, 3+4
  ps_filter(sample == "water_CTD" | sample == "trap_fix") %>%
  ps_filter(cycle_name != "SA-Sc-B") %>%
  # ps_filter((sample == "trap_fix") | (sample == "water_CTD" & depth <= 20)) %>%
  ps_mutate(sample_depth = case_when(sample == "trap_fix" ~ paste(sample, depth_category, sep = "_"), 
                                     # add label for depth only for fixed traps
                                     sample == "water_CTD" ~ sample)) %>%
  ps_mutate(sample_depth = case_when(sample_depth == "trap_fix_1" ~ "trap_fix_1_2",
                                     sample_depth == "trap_fix_2" ~ "trap_fix_1_2",
                                     sample_depth == "trap_fix_3" ~ "trap_fix_3_4",
                                     sample_depth == "trap_fix_4" ~ "trap_fix_3_4",
                                     TRUE ~ as.character(sample_depth))) %>%
  ps_mutate(sample_depth_wm = paste(sample_depth, water_mass, sep = "_"))  %>%
  tax_filter(min_total_abundance = 11)

deseq.subset

sample <- as.data.frame(deseq.subset@sam_data)

```
# list of ASVs from sediment
```{r}
ps_core <- ps %>% 
   ps_filter(sample == "core")
ps_long <- phyloseq_transform_to_long(ps_core)

core_asvs <- ps_long %>%
  select(ASV, water_mass) %>%
  unique() %>%
  mutate(sediment = "detected")

core_asvs_ST <- core_asvs %>%
  filter(water_mass == "ST")

core_asvs_SA <- core_asvs %>%
  filter(water_mass == "SA")
```

# ST analysis
Subset ST water mass, filter ASVs for minimum prevalence 10%, and only asvs present in all sample groups.
```{r}

deseq.st <- deseq.subset %>%
  ps_filter(water_mass == "ST") %>%
  tax_filter(min_prevalence = 0.1)

# 1. Define your grouping variable (replace 'Group' with your actual column name)
group_var <- "sample_depth"

# 2. Get a list of taxa present in EACH group
# We split the phyloseq object by group and identify taxa with at least 1 read
taxa_by_group <- sample_data(deseq.st)[[group_var]] %>% 
  unique() %>% 
  map(function(x) {
    # Subset to one group at a time
    ps_sub <- prune_samples(sample_data(deseq.st)[[group_var]] == x, deseq.st)
    # Get names of taxa that have a sum > 0 in this specific group
    taxa_names(prune_taxa(taxa_sums(ps_sub) > 0, ps_sub))
  })

# 3. Find the intersection (taxa present in all lists)
common_taxa <- purrr::reduce(taxa_by_group, intersect)

# 4. Prune the original phyloseq object to keep only these taxa
deseq.st.filt <- prune_taxa(common_taxa, deseq.st)

deseq.st.filt

# #no. of samples in each group
deseq.st.filt@sam_data %>%
  group_by(sample_depth_wm) %>%
  summarise(n=n())
# 
# junk <- as.data.frame(deseq.st@sam_data)
```


run aldex analysis separately for export and transfer.
```{r}
ps <- deseq.st.filt %>%
  ps_filter(sample_depth != "trap_fix_3_4")

res_st.export<- phyloseq_run_aldex(ps) 
  
ps <- deseq.st.filt %>%
  ps_filter(sample_depth != "water_CTD")

res_st.transfer <- phyloseq_run_aldex(ps) 
```

plot 
```{r}
res_filt_export <- res_st.export %>%
  mutate(is_significant_export = (overlap <= 0.4 & abs(effect) > 0.25)) %>%
  # mutate(is_significant_export = (overlap <= 0.4 & abs(effect) >= 0.25 & abs(effect) <= 0.5)) %>%
  mutate(diff.btw_export = diff.btw * (-1))  %>%
  select(is_significant_export, diff.btw_export, ASV, domain:species)

res_filt_transfer <- res_st.transfer %>%
  mutate(is_significant_transfer = (overlap <= 0.4 & abs(effect) > 0.25)) %>%
  # mutate(is_borderline = (overlap <= 0.4 & abs(effect) >= 0.25 & abs(effect) <= 0.4)
  mutate(diff.btw_transfer = diff.btw)  %>%
  select(is_significant_transfer, diff.btw_transfer, ASV, domain:species)

res_filt_join <- full_join(res_filt_export, res_filt_transfer %>% select(ASV, diff.btw_transfer, is_significant_transfer), by = join_by(ASV)) %>%
  filter(is_significant_export | is_significant_transfer) %>%
  full_join(core_asvs_ST) %>%
  mutate(sediment = coalesce(sediment, "not detected")) %>%
  filter(!(is.na(diff.btw_export))) 
```

```{r}

g1 <- res_filt_join %>%
  # filter(subdivision != "Dinoflagellata") %>%
  filter(is_significant_export) %>%
  ggplot(aes(x=fct_rev(fct_inorder(class)), y=diff.btw_export)) + 
  geom_point(aes(shape=sediment, size=sediment, fill=subdivision), colour="black") +
  theme(axis.text.x = element_text(angle = -90, hjust = 0, vjust=0.5))+
  scale_fill_manual(values=divisionPalette) +
  geom_hline(yintercept = 0, linetype="solid") +
  coord_flip() +
  theme_bw() +
  theme(axis.text.x = element_text(size = 10),
        axis.title.x =element_text(size=10),
        axis.text.y = element_text(size = 8),
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 10),
        legend.position = "right"
        # legend.position = "none"
        ) +
  ylab("log2 fold change - Water CTD <--> Upper fixed traps") +
  ggtitle("Export efficiency") +
  theme(strip.text.y = element_blank(),
        strip.background = element_blank(),
        panel.spacing.x = unit(0,"lines"),
        panel.spacing.y = unit(0, "lines"),
        panel.border = element_blank(),
        legend.title = element_markdown()) +
  facet_grid(subdivision~., scales = "free", space = "free", switch = "y") +
  # scale_shape_manual(values=c(3, 16, 17)) +
  scale_size_manual(values=c(3, 2.5)) +
  scale_shape_manual(values = c(24,21))
g1
# pdf("deseq_legend.pdf", height= 10, width=7) ; plot(g1) ; dev.off()


g1 <- res_filt_join %>%
  # filter(subdivision != "Dinoflagellata") %>%
  filter(is_significant_transfer) %>%
  ggplot(aes(x=fct_rev(fct_inorder(class)), y=diff.btw_transfer)) + 
  geom_point(aes(shape=sediment, size=sediment, fill=subdivision), colour="black") +
  theme(axis.text.x = element_text(angle = -90, hjust = 0, vjust=0.5))+
  scale_fill_manual(values=divisionPalette) +
  geom_hline(yintercept = 0, linetype="solid") +
  coord_flip() +
  theme_bw() +
  theme(axis.text.x = element_text(size = 10),
        axis.title.x =element_text(size=10),
        axis.text.y = element_text(size = 8),
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 10),
        legend.position = "right"
        # legend.position = "none"
        ) +
  ylab("log2 fold change - Water CTD <--> Upper fixed traps") +
  ggtitle("Export efficiency") +
  theme(strip.text.y = element_blank(),
        strip.background = element_blank(),
        panel.spacing.x = unit(0,"lines"),
        panel.spacing.y = unit(0, "lines"),
        panel.border = element_blank(),
        legend.title = element_markdown()) +
  facet_grid(subdivision~., scales = "free", space = "free", switch = "y") +
  # scale_shape_manual(values=c(3, 16, 17)) +
  scale_size_manual(values=c(3, 2.5)) +
  scale_shape_manual(values = c(24,21))
g1
# pdf("deseq_legend.pdf", height= 10, width=7) ; plot(g1) ; dev.off()

g3 <- res_filt_join %>% 
  filter(subdivision != "Dinoflagellata") %>%
  filter(is_significant_export & is_significant_transfer) %>%
  ggplot(aes(x = diff.btw_export, y = diff.btw_transfer)) +
  geom_point(aes(shape=sediment, size=sediment, fill=subdivision), colour="black") +
  geom_vline(xintercept = 0, linetype="solid") +  
  geom_hline(yintercept = 0, linetype="solid") +  
  xlab("Export efficiency log2 fold change - Water CTD <--> Upper fixed traps") +
  ylab("Transfer efficiency log2 fold change - Upper <--> Lower fixed traps") +
  scale_fill_manual(values=divisionPalette) +
  scale_colour_manual(values=divisionPalette)+
  theme(axis.text.x = element_text(size = 9),
        axis.title.x =element_text(size=10),
        axis.text.y = element_text(size = 9),
        legend.title = element_text(size = 12),
        legend.text = element_text(size = 12),
        legend.position = "right") +
  scale_size_manual(values=c(5, 2)) +
  scale_shape_manual(values = c(24,21))+
  coord_fixed() +
  ggtitle("Subtropical") +
  scale_y_continuous(limits = c(-10, 10))+
  scale_x_continuous(limits = c(-10, 10))

g3

```


## ST- ASV raw data supp fig
```{r}

target_asvs <- res_filt_join %>%
  filter(subdivision != "Dinoflagellata") %>%
  filter(is_significant_export & is_significant_transfer) %>%
  pull(ASV) 

ps_rel <- transform_sample_counts(deseq.st.filt, function(x) x / sum(x)) %>%
  psmelt() 

plot_df <- ps_rel %>%
  filter(OTU %in% target_asvs)  %>%
  mutate(sample_depth = factor(sample_depth, 
                               levels = c("water_CTD", "trap_fix_1_2", "trap_fix_3_4"))) %>%
  mutate(label = paste0(subdivision, " | ", genus, "\n", OTU))

ggplot(plot_df, aes(x = sample_depth, y = Abundance, fill = sample_depth)) +
  geom_boxplot(alpha = 0.2, outlier.shape = NA) + 
  geom_jitter(width = 0.2, shape = 21, size = 3) +
  facet_wrap(~label, scales = "free_y") + 
  theme_bw() +
  labs(y = "Relative Abundance", x = "Sample Depth")

```

# SA analysis
```{r}

deseq.sa <- deseq.subset %>%
  ps_filter(water_mass == "SA") %>%
  tax_filter(min_prevalence = 0.1)

# 1. Define your grouping variable (replace 'Group' with your actual column name)
group_var <- "sample_depth"

# 2. Get a list of taxa present in EACH group
# We split the phyloseq object by group and identify taxa with at least 1 read
taxa_by_group <- sample_data(deseq.sa)[[group_var]] %>% 
  unique() %>% 
  map(function(x) {
    # Subset to one group at a time
    ps_sub <- prune_samples(sample_data(deseq.sa)[[group_var]] == x, deseq.sa)
    # Get names of taxa that have a sum > 0 in this specific group
    taxa_names(prune_taxa(taxa_sums(ps_sub) > 0, ps_sub))
  })

# 3. Find the intersection (taxa present in all lists)
common_taxa <- purrr::reduce(taxa_by_group, intersect)

# 4. Prune the original phyloseq object to keep only these taxa
deseq.sa.filt <- prune_taxa(common_taxa, deseq.sa)

deseq.sa.filt

# #no. of samples in each group
deseq.sa.filt@sam_data %>%
  group_by(sample_depth_wm) %>%
  summarise(n=n())
# 
# junk <- as.data.frame(deseq.st@sam_data)
```



```{r}
ps <- deseq.sa.filt %>%
  ps_filter(sample_depth != "trap_fix_3_4")

res_sa.export<- phyloseq_run_aldex(ps)
  
ps <- deseq.sa.filt %>%
  ps_filter(sample_depth != "water_CTD")

res_sa.transfer <- phyloseq_run_aldex(ps)

```

```{r}

res_filt_sa.export <- res_sa.export %>%
  mutate(is_significant_export = (overlap <= 0.4 & abs(effect) > 0.25)) %>%
  mutate(diff.btw_export = diff.btw * (-1))  %>%
  select(is_significant_export, diff.btw_export, ASV, domain:species)

res_filt_sa.transfer <- res_sa.transfer %>%
  mutate(is_significant_transfer = (overlap <= 0.4 & abs(effect) > 0.25)) %>%
  mutate(diff.btw_transfer = diff.btw)  %>%
  select(is_significant_transfer, diff.btw_transfer, ASV, domain:species)

res_filt_sa.join <- full_join(res_filt_sa.export, res_filt_sa.transfer %>% select(ASV, diff.btw_transfer, is_significant_transfer), by = join_by(ASV)) %>%
  filter(is_significant_export | is_significant_transfer)%>%
  full_join(core_asvs_SA) %>%
  mutate(sediment = coalesce(sediment, "not detected")) %>%
  filter(!(is.na(diff.btw_export))) 



g1 <- res_filt_sa.join %>%
  filter(is_significant_export) %>%
  # filter(subdivision != "Dinoflagellata") %>%
  ggplot(aes(x=fct_rev(fct_inorder(class)), y=diff.btw_export)) + 
  geom_point(aes(shape=sediment, size=sediment, fill=subdivision), colour="black") +
  theme(axis.text.x = element_text(angle = -90, hjust = 0, vjust=0.5))+
  scale_fill_manual(values=divisionPalette) +
  geom_hline(yintercept = 0, linetype="solid") +
  coord_flip() +
  theme_bw() +
  theme(axis.text.x = element_text(size = 10),
        axis.title.x =element_text(size=10),
        axis.text.y = element_text(size = 8),
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 10),
        legend.position = "right"
        # legend.position = "none"
        ) +
  ylab("log2 fold change - Water CTD <--> Upper fixed traps") +
  ggtitle("Export efficiency") +
  theme(strip.text.y = element_blank(),
        strip.background = element_blank(),
        panel.spacing.x = unit(0,"lines"),
        panel.spacing.y = unit(0, "lines"),
        panel.border = element_blank(),
        legend.title = element_markdown()) +
  facet_grid(subdivision~., scales = "free", space = "free", switch = "y") +
  # scale_shape_manual(values=c(3, 16, 17)) +
  scale_size_manual(values=c(3, 2.5)) +
  scale_shape_manual(values = c(24,21))
g1
# pdf("deseq_legend.pdf", height= 10, width=7) ; plot(g1) ; dev.off()


g2 <- res_filt_sa.join %>%
  filter(is_significant_transfer) %>%
  # filter(subdivision != "Dinoflagellata") %>%
  ggplot(aes(x=fct_rev(fct_inorder(class)), y=diff.btw_transfer)) + 
  geom_point(aes(shape=sediment, size=sediment, fill=subdivision), colour="black") +
  theme(axis.text.x = element_text(angle = -90, hjust = 0, vjust=0.5))+
  scale_fill_manual(values=divisionPalette) +
  geom_hline(yintercept = 0, linetype="solid") +
  coord_flip() +
  theme_bw() +
  theme(axis.text.x = element_text(size = 10),
        axis.title.x =element_text(size=10),
        axis.text.y = element_text(size = 8),
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 10),
        legend.position = "right"
        # legend.position = "none"
        ) +
  ylab("log2 fold change - Upper fixed traps <--> Lower fixed traps") +
  ggtitle("Transfer") +
  theme(strip.text.y = element_blank(),
        strip.background = element_blank(),
        panel.spacing.x = unit(0,"lines"),
        panel.spacing.y = unit(0, "lines"),
        panel.border = element_blank(),
        legend.title = element_markdown()) +
  facet_grid(subdivision~., scales = "free", space = "free", switch = "y") +
  # scale_shape_manual(values=c(3, 16, 17)) +
  scale_size_manual(values=c(3, 2.5)) +
  scale_shape_manual(values = c(24,21))
g2
# pdf("deseq_legend.pdf", height= 10, width=7) ; plot(g1) ; dev.off()

g3 <- res_filt_sa.join %>% 
  filter(subdivision != "Dinoflagellata") %>%
  filter(is_significant_export & is_significant_transfer) %>%
  ggplot(aes(x = diff.btw_export, y = diff.btw_transfer)) +
  geom_point(aes(shape=sediment, size=sediment, fill=subdivision), colour="black") +
  geom_vline(xintercept = 0, linetype="solid") +  
  geom_hline(yintercept = 0, linetype="solid") +  
  xlab("Export efficiency log2 fold change - Water CTD <--> Upper fixed traps") +
  ylab("Transfer efficiency log2 fold change - Upper <--> Lower fixed traps") +
  scale_fill_manual(values=divisionPalette) +
  scale_colour_manual(values=divisionPalette)+
  theme(axis.text.x = element_text(size = 9),
        axis.title.x =element_text(size=10),
        axis.text.y = element_text(size = 9),
        legend.title = element_text(size = 12),
        legend.text = element_text(size = 12),
        legend.position = "right") +
  scale_size_manual(values=c(2.5, 2)) +
  scale_shape_manual(values = c(24,21))+
  coord_fixed() +
  ggtitle("Subantarctic") +
  scale_y_continuous(limits = c(-10, 10))+
  scale_x_continuous(limits = c(-10, 10))

g3

g4 <- res_filt_sa.join %>% 
  filter(subdivision == "Dinoflagellata") %>%
  filter(is_significant_export & is_significant_transfer) %>%
  ggplot(aes(x = diff.btw_export, y = diff.btw_transfer)) +
  geom_point(aes(shape=sediment, size=sediment, fill=class), colour="black") +
  geom_vline(xintercept = 0, linetype="solid") +  
  geom_hline(yintercept = 0, linetype="solid") +  
  xlab("Export efficiency log2 fold change - Water CTD <--> Upper fixed traps") +
  ylab("Transfer efficiency log2 fold change - Upper <--> Lower fixed traps") +
  scale_fill_manual(values=divisionPalette) +
  scale_colour_manual(values=divisionPalette)+
  theme(axis.text.x = element_text(size = 9),
        axis.title.x =element_text(size=10),
        axis.text.y = element_text(size = 9),
        legend.title = element_text(size = 12),
        legend.text = element_text(size = 12),
        legend.position = "right") +
  scale_size_manual(values=c(2.5, 2)) +
  scale_shape_manual(values = c(24,21))+
  coord_fixed() +
  ggtitle("Subantarctic") +
  scale_y_continuous(limits = c(-10, 10))+
  scale_x_continuous(limits = c(-10, 10))

g4
```

## ST- ASV raw data supp fig
```{r}

target_asvs <- res_filt_sa.join %>%
  filter(subdivision != "Dinoflagellata") %>%
  filter(is_significant_export & is_significant_transfer) %>%
  pull(ASV) 

# 1. Convert to relative abundance first (so Y-axis is 0 to 1)
ps_rel <- transform_sample_counts(deseq.sa.filt, function(x) x / sum(x)) %>%
  psmelt() 

# 3. Filter for your specific ASV IDs
plot_df <- ps_rel %>%
  filter(OTU %in% target_asvs)  %>%# 'OTU' is the default column name for ASV IDs in psmelt
  mutate(sample_depth = factor(sample_depth, 
                               levels = c("water_CTD", "trap_fix_1_2", "trap_fix_3_4"))) %>%
   mutate(label = paste0(subdivision, " | ", genus, "\n", OTU))

# 4. Create the simple dot plot
ggplot(plot_df, aes(x = sample_depth, y = Abundance, fill = sample_depth)) +
  geom_boxplot(alpha = 0.2, outlier.shape = NA) + 
  geom_jitter(width = 0.2, shape = 21, size = 3) +
  facet_wrap(~label, scales = "free_y") + 
  theme_bw() +
  labs(y = "Relative Abundance", x = "Sample Depth")
```

```{r}

res_list <- list(
  "Subtropical Transfer" = res_st.transfer,
  "Subtropical Export"   = res_st.export,
  "Subantarctic Export"   = res_sa.export,
  "Subantarctic Transfer" = res_sa.transfer
)

# Create an empty list to hold the resulting plots
plot_list <- list()

df_names <- names(res_list)

for (name in df_names) {
  
  # Get the current data frame
  df <- res_list[[name]]
  
  # Build the plot
  p <- ggplot(df, aes(x = effect)) +
    geom_histogram(aes(fill = abs(effect) > 0.3), 
                   bins = 60, color = "white") +
    scale_fill_manual(values = c("gray80", "steelblue"), 
                      name = "Passed Threshold", 
                      labels = c("Noise (<0.3)", "Potential Hit (>0.3)")) +
    geom_vline(xintercept = c(-0.3, 0.3), linetype = "dashed", color = "orange") +
    geom_vline(xintercept = c(-1.0, 1.0), linetype = "solid", color = "darkgreen") +
    theme_minimal() +
    labs(title = paste("Effect Size Distribution:", name),
         x = "Effect Size (diff.btw / max.diff.win)",
         y = "Number of ASVs") +
    theme(legend.position = "bottom")
  
  print(p)
}






# ggplot(res_st.transfer, aes(x = effect)) +
#   geom_histogram(aes(fill = abs(effect) > 0.3), 
#                  bins = 60, color = "white") +
#   scale_fill_manual(values = c("gray80", "steelblue"), 
#                     name = "Passed Threshold", 
#                     labels = c("Noise (<0.5)", "Potential Hit (>0.5)")) +
#   geom_vline(xintercept = c(-0.5, 0.5, -1.0, 1.0), 
#              linetype = "dashed", color = "red") +
#   theme_minimal() +
#   labs(title = "ALDEx2 Effect Size Distribution",
#        x = "Effect Size (diff.btw / max.diff.win)",
#        y = "Number of ASVs")

```










```{r}



target_asvs <- res_filt_join %>%
  filter(subdivision != "Dinoflagellata") %>%
  filter(is_significant_export & is_significant_transfer) %>%
  pull(ASV) 

# 1. Prepare data (Relative Abundance)
ps_rel_df <- transform_sample_counts(deseq.st.filt, function(x) x / sum(x)) %>%
  psmelt() 

# 2. Filter for significant ASVs and keep ONLY water_CTD samples
plot_df <- ps_rel_df %>%
  filter(OTU %in% target_asvs) %>%
  filter(sample_depth == "water_CTD") %>% # Keep only CTD water
  mutate(label = paste0(subdivision, " | ", genus, " (", OTU, ")")) %>%
  # Ensure depth is treated as a discrete factor for the x-axis
  mutate(depth = factor(depth)) 

# 3. Create the plot with Depth on the X-axis
ggplot(plot_df, aes(x = depth, y = Abundance, fill = depth)) +
  geom_boxplot(alpha = 0.2, outlier.shape = NA) + 
  geom_jitter(width = 0.2, shape = 21, size = 3, alpha = 0.8) +
  facet_wrap(~label, scales = "free_y") + 
  theme_bw() +
  labs(title = "Water CTD Profile: Relative Abundance by Depth",
       y = "Relative Abundance", 
       x = "Depth (m)") +
  theme(axis.text.x = element_text(size = 9),
        strip.text = element_text(size = 7, face = "bold"),
        legend.position = "none")

```

# multigroup
```{r}
counts <- as(otu_table(deseq.st.filt), "matrix")

# Ensure taxa are rows
if (!taxa_are_rows(deseq.st.filt)) {
  counts <- t(counts)
}

meta <- sample_data(deseq.st.filt)
conds_f <- factor(meta$sample_depth, levels = c("trap_fix_1_2", "trap_fix_3_4", "water_CTD"))


mm <- model.matrix(~ conds_f)

x <- aldex.clr(counts, mm, mc.samples=128, verbose=FALSE, gamma =0.2)

x.glm <- aldex.glm(x, mm) 
x.glm.effect <- aldex.glm.effect(x)

# 5. Combine results
x.glm.all <- data.frame(x.glm, x.glm.effect) %>%
  rownames_to_column(var = "ASV")

taxa <- as.data.frame(tax_table(deseq.st.filt))

x.glm.taxa <- full_join(x.glm.all, taxa)

aldex.glm.plot(x.glm, eff=x.glm.effect, contrast='conds_fwater_CTD', type='MW', test='fdr')

```


```{r}
res_filt <- x.glm.taxa %>%
  # filter(conds_fwater_CTD.overlap<=0.25) %>%
  # filter(conds_ftrap_fix_3_4.overlap<=0.25) %>%
  filter(conds_fwater_CTD.effect >0.5 |conds_fwater_CTD.effect < -0.5) %>%
  filter(conds_ftrap_fix_3_4.effect >0.5 |conds_ftrap_fix_3_4.effect < -0.5)

g1 <- res_filt %>%
  # filter(subdivision != "Dinoflagellata") %>%
  ggplot(aes(x=fct_rev(fct_inorder(class)), y=conds_fwater_CTD.diff.btw)) + 
  geom_point(aes(fill=class), colour="black") +
  theme(axis.text.x = element_text(angle = -90, hjust = 0, vjust=0.5))+
  scale_fill_manual(values=divisionPalette) +
  geom_hline(yintercept = 0, linetype="solid") +
  coord_flip() +
  theme_bw() +
  theme(axis.text.x = element_text(size = 10),
        axis.title.x =element_text(size=10),
        axis.text.y = element_text(size = 8),
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 10),
        legend.position = "right"
        # legend.position = "none"
        ) +
  ylab("log2 fold change - Upper fixed traps<--> Water CTD ") +
  ggtitle("Export efficiency") +
  theme(strip.text.y = element_blank(),
        strip.background = element_blank(),
        panel.spacing.x = unit(0,"lines"),
        panel.spacing.y = unit(0, "lines"),
        panel.border = element_blank(),
        legend.title = element_markdown()) +
  facet_grid(subdivision~., scales = "free", space = "free", switch = "y") +
  # scale_shape_manual(values=c(3, 16, 17)) +
  scale_size_manual(values=c(3, 2.5)) +
  scale_shape_manual(values = c(24,21))
g1

g2 <- res_filt %>%
  # filter(subdivision != "Dinoflagellata") %>%
  ggplot(aes(x=fct_rev(fct_inorder(class)), y=conds_ftrap_fix_3_4.diff.btw)) + 
  geom_point(aes(fill=class), colour="black") +
  theme(axis.text.x = element_text(angle = -90, hjust = 0, vjust=0.5))+
  scale_fill_manual(values=divisionPalette) +
  geom_hline(yintercept = 0, linetype="solid") +
  coord_flip() +
  theme_bw() +
  theme(axis.text.x = element_text(size = 10),
        axis.title.x =element_text(size=10),
        axis.text.y = element_text(size = 8),
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 10),
        legend.position = "right"
        # legend.position = "none"
        ) +
  ylab("log2 fold change - Upper fixed traps  <--> lower fixed traps ") +
  ggtitle("Transfer efficiency") +
  theme(strip.text.y = element_blank(),
        strip.background = element_blank(),
        panel.spacing.x = unit(0,"lines"),
        panel.spacing.y = unit(0, "lines"),
        panel.border = element_blank(),
        legend.title = element_markdown()) +
  facet_grid(subdivision~., scales = "free", space = "free", switch = "y") +
  # scale_shape_manual(values=c(3, 16, 17)) +
  scale_size_manual(values=c(3, 2.5)) +
  scale_shape_manual(values = c(24,21))
g2
# pdf("deseq_legend.pdf", height= 10, width=7) ; plot(g1) ; dev.off()

```

# ancom
```{r}
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("ANCOMBC")

library(CVXR)
library(ANCOMBC)
library(mia)

tse <- makeTreeSummarizedExperimentFromPhyloseq(deseq.st)

output <- ancombc2(
  data = tse,
  assay_name = "counts",
  tax_level = NULL,

  fix_formula = "sample_depth",   # only variable
  group = "sample_depth",                  # no grouping

  p_adj_method = "holm",
  pseudo_sens = TRUE,

  # prv_cut = 0.10,
  # lib_cut = 1000,
  s0_perc = 0.05,

  struc_zero = FALSE,
  neg_lb = FALSE,

  alpha = 0.05,
  n_cl = 2,
  verbose = TRUE,

  global = FALSE,
  pairwise = TRUE   
)

res_prim <- output$res %>%
  dplyr::rename(ASV = taxon)
res_taxa <- full_join(res_prim, taxa)

tax <- as.data.frame(rowData(tse))

tax$ASV <- rownames(tax)
res_prim$ASV <- rownames(res_prim)

res_prim_tax <- merge(res_prim, tax, by = "ASV")
```

